### ISSUE TITLE
How to set the terminal password?

### ISSUE THREAD

**Issue by Proggopogo** [Portalum/Portalum.Zvt#1]
Hello @tinohager ! I am currently attempting to create a little terminal application for a payment terminal using the Zvt protocol with your Portalum library in C#. I ran into an issue with that tho. The terminal requires a login password upon first starting of the terminal. Its a simple six numbers sequence. I didn't find any function in your library that allows a login process to take place. Do you have any information for me that could help me accomplish that? I tried to find a documentation to your project, but to no avail, which is why I'm trying to reach you personally.

**Comment by tinohager** [comment]
hi you can set the password on the constructor

```
public ZvtClient(
            IDeviceCommunication deviceCommunication,
            ILogger<ZvtClient> logger = default,
            int password = 000000,
            IReceiveHandler receiveHandler = default,
            Language language = Language.English)
        {
```

**Comment by tinohager** [comment]
We would still appreciate feedback when you have tested your terminal whether everything works? Information about the tested terminal (manufacturer, model) would be great.

**Comment by Proggopogo** [comment]
I will give you all the neccessary informations as soon as I've tested your solution. Thank you for your help so far!

**Comment by Proggopogo** [comment]
After having tried the following code:

```
using System;
using Portalum.Zvt;
using Portalum;
using Microsoft.Extensions.Logging;


namespace TrefonPPay
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.WriteLine("Bitte geben sie den zu bezahlenden Betrag ein: ");
            string amount = Console.ReadLine();
            decimal Amount = Convert.ToDecimal(amount);
            Login("192.168.0.77", xxxxxx, xxxxxx, Amount);
        }

        public static async void Login(string IP, int port, int password, decimal amount)
        {
            var deviceComm = new TcpNetworkDeviceCommunication(IP, port: port);
            await deviceComm.ConnectAsync();
            ILogger<ZvtClient> logger = default;
            IReceiveHandler handler = default;
            using var ZvtClient = new ZvtClient(deviceComm, logger, password, handler, Language.German);
            await ZvtClient.PaymentAsync(amount);
        }
    }
}
```

The terminal remained absolutely silent. The terminal is a verifone GE 3411. The Zvt protocol is supported, and the device works fine with the settings replaced by x'es in the application the vendor supplied to me. Any suggestions? I have checked IP address and port, they are correct, so thats not the issue. Any ideas that could help me?

**Comment by tinohager** [comment]
what ist the result of `PaymentAsync` ?

**Comment by Proggopogo** [comment]
Nothing happens. It just runs through without any results.

**Comment by tinohager** [comment]
`public async Task<CommandResponse> PaymentAsync(decimal amount)` what is the CommandResponse?

**Comment by tinohager** [comment]
`public async Task<CommandResponse> RegistrationAsync(RegistrationConfig registrationConfig)` ?

**Comment by Proggopogo** [comment]
I am sorry, I have never worked with Command Responses before. Can you quickly modify my code to what you want it to do so I can implement it and give you a result?

**Comment by tinohager** [comment]
```
public static async void Login(string IP, int port, int password, decimal amount)
{
    var deviceComm = new TcpNetworkDeviceCommunication(IP, port: port);
    await deviceComm.ConnectAsync();
    ILogger<ZvtClient> logger = default;
    IReceiveHandler handler = default;
    using var ZvtClient = new ZvtClient(deviceComm, logger, password, handler, Language.German);
    var response1 = await ZvtClient.RegistrationAsync(new RegistrationConfig());
    Console.WriteLine(response1);
    var response2 = await ZvtClient.PaymentAsync(amount);
    Console.WriteLine(response2);
}
```

**Comment by Proggopogo** [comment]
Alright, I have tried your code, and there are no responses.

**Comment by Proggopogo** [comment]
The communication worked for a split second, but then closed again immediately.

**Comment by Proggopogo** [comment]
Alright I figured it out. The library seems to have issues with decimal numbers. My company only allows me to push small amounts of cash back and forth. Trying it with 0.01€ doesn't work, but 1.00€ does.

**Comment by Proggopogo** [comment]
I ran into another issue. The code you have provided also doesn't allow a payment. I was able to push a payment through, but as soon as I inserted my card and entered the pin, the terminal responded with "Payment not possible. Please remove card."

**Comment by tinohager** [comment]
have you register the events?

```
        public event Action<StatusInformation> StatusInformationReceived;
        public event Action<string> IntermediateStatusInformationReceived;
        public event Action<PrintLineInfo> LineReceived;
        public event Action<ReceiptInfo> ReceiptReceived;
```

**Comment by tinohager** [comment]
`await ZvtClient.PaymentAsync(0.01M);` fails?

**Comment by Proggopogo** [comment]
`await ZvtClient.PaymentAsync(0.01M);` Sometimes fails, and it sometimes doesn't, and I didn't even know about the event triggers in the librbary. As I've already mentioned, documentation isn't really findable.

**Comment by tinohager** [comment]
There is a TestUi project where you can take a close look at the code.

**Comment by Proggopogo** [comment]
I will give that a look. I personally think that these informations are important tho and should be part of the README.

**Comment by tinohager** [comment]
sorry it is still a very new project the documentation will surely grow in the future

**Comment by Proggopogo** [comment]
That's alright. If I run into any other issues I'll let you know. Maybe my experiences and your expertise could help some people in the future.

**Comment by tinohager** [comment]
So does it work?

**Comment by tinohager** [comment]
I have added a few more points to the documentation

**Comment by Proggopogo** [comment]
Hello @tinohager ! I apologize for my late reply, I was sick the remainder of the previous week. To your question:

Yes, it does work, but it's not very reliant. Issuing a payment works once every 5 tries. That might be because of the async nature of the library. The command line application I wrote ends as soon as an await statement is called. I will write a windows forms application to test the library further. Maybe that will solve the problem.

**Comment by tinohager** [comment]
Can you show the code? Maybe you still have a bug in it?

**Comment by Proggopogo** [comment]
IT's the same code as the last time, with your refactoring. 

`using System;
using Portalum.Zvt;
using Portalum;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Threading;

namespace TrefonPPay
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.WriteLine("Bitte geben sie den zu bezahlenden Betrag ein: ");
            string amount = Console.ReadLine();
            decimal Amount = Convert.ToDecimal(amount);
            Console.WriteLine(Amount);
            Login("192.168.0.77", 22000, 000000, Amount);
        }

        public static async void Login(string IP, int port, int password, decimal amount)
        {
            var deviceComm = new TcpNetworkDeviceCommunication(IP, port: port);
            await deviceComm.ConnectAsync();
            ILogger<ZvtClient> logger = default;
            IReceiveHandler handler = default;
            using var ZvtClient = new ZvtClient(deviceComm, logger, password, handler, Language.German);
            await ZvtClient.RegistrationAsync(new RegistrationConfig());
            Thread.Sleep(1000);
            //Console.WriteLine(response1);
            Console.WriteLine(amount);
            Thread.Sleep(5000);
            await ZvtClient.PaymentAsync(amount);
            //Console.WriteLine(response2);
        }

    }
}
`

However, good news is that the login function works. But as mentioned earlier, as soon as the first await statement is called, the program ends. Also, I have another question regarding a different topic. Should I open a new issue for that or ask here?

**Comment by tinohager** [comment]
try this

```
using Microsoft.Extensions.Logging;
using Portalum.Zvt;
using System;
using System.Threading.Tasks;

namespace TrefonPPay
{
    class Program
    {
        static async Task Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.WriteLine("Bitte geben sie den zu bezahlenden Betrag ein: ");
            var tempAmount = Console.ReadLine();
            var amount = Convert.ToDecimal(tempAmount);

            Console.WriteLine(amount);
            await LoginAsync("192.168.0.77", 22000, 000000, amount);

            Console.WriteLine("Payment done");
        }

        public static async Task LoginAsync(string ipAddress, int port, int password, decimal amount)
        {
            ILogger<ZvtClient> logger = default;

            using var deviceCommunication = new TcpNetworkDeviceCommunication(ipAddress, port: port);
            await deviceCommunication.ConnectAsync();

            using var ZvtClient = new ZvtClient(deviceCommunication, logger, password: password, language: Language.German);

            var response = await ZvtClient.RegistrationAsync(new RegistrationConfig());
            Console.WriteLine(response.State);

            response = await ZvtClient.PaymentAsync(amount);
            Console.WriteLine(response.State);
        }
    }
}
```

**Comment by Proggopogo** [comment]
That worked flawlessly! Thank you for your help! That should give me something to work with. The Verifone UX300/301 should be listet under working devices. I will open another issue for my other problem, but until now, thanks a lot.

**Comment by tinohager** [comment]
Do they produce vending machines?

**Comment by Proggopogo** [comment]
I added a picture of the cash terminal I am currently working with. It looks exactly like that. The plan is to include this terminal in a future vending machine my company is building.

![UX Series](https://user-images.githubusercontent.com/50118317/142834768-873e37be-6032-457b-a236-6787e3d6bc45.png)

**Comment by tinohager** [comment]
We are also interested in vending machines may I know who they work for?

**Comment by Proggopogo** [comment]
The company I am working for or the company that's producing the terninals?

**Comment by tinohager** [comment]
The company they work for

**Comment by Proggopogo** [comment]
The VeriFone Systems Inc.

**Comment by tinohager** [comment]
Do you work for the payment terminal manufacturer?

**Comment by Proggopogo** [comment]
No, I work for a company that is going to use the terminal in future installations.

**Comment by tinohager** [comment]
And what is the name of the company? 😃

**Comment by Proggopogo** [comment]
Trefon electronic Gmbh.
