### ISSUE TITLE
Issue in Handling Terminal Responses

### ISSUE THREAD

**Issue by SRouven** [Portalum/Portalum.Zvt#10]
Hello, 

first of all, great project. Vielen Dank, es war für mich auch der Anstoß hier wirklich auch mal aktiv teil zu nehmen :) 

I get issues, when working with ingenico PT´s over TCP. I´m mainly working with the Desk/3500 and Link/2500. 
When i call the registration, in most of my calls i´m getting an error and get problems in further communication. This also happens with the "Portalum ZVT ControlPanel".

In ZvtCommunication.ProcessDataReceived, there is no handling for a Buffer that contains the ACK (80-00-00) AND a following Completion. 
The Buffer that is recieved, i my cases, contains the ACK and Completiondata (22 byte long). But this can not be identified  as an ACK in ZvtCommunication.SendCommandAsync (l. 121) and does never get processed by a recievehandler.

![Register](https://user-images.githubusercontent.com/23655900/158554862-9a3c4140-b5ed-4f43-9fd1-4bfeff4092b0.jpg)

I surely can provide you with more information, if needed.

**Comment by tinohager** [comment]
Thanks for the description I will get back to you in the next few days

**Comment by tinohager** [comment]
Hi can you check this version?
https://github.com/Portalum/Portalum.Zvt/tree/fix/data-fragmentation

**Comment by tinohager** [comment]
Were they able to review my changes?

**Comment by SRouven** [comment]
I´m going to. I´m a little short in time, atm.

**Comment by SRouven** [comment]
HI, i checked the changes and don't have this issue anymore.
