### ISSUE TITLE
Feature Request: Partial Capture

### ISSUE THREAD

**Issue by MLDMoritz** [Portalum/Portalum.Zvt#11]
Hey there,

I am looking for a solution where we can do partial capture of funds. 

An implementation can be found here (2.2.6 Status-Information):

![image](https://user-images.githubusercontent.com/46711821/160254765-760b9149-e6a3-4ba8-a324-0a53eb59b8d4.png)
![image](https://user-images.githubusercontent.com/46711821/160254842-e0fe2fea-f6e3-4d52-a12c-efd7c35e3455.png)

However this library automatically approves the authorization, I cannot intercept this it seems. I tried spamming this:

```C#
var periodicTimer= new PeriodicTimer(TimeSpan.FromMilliseconds(500));
while (await periodicTimer.WaitForNextTickAsync())
{
    var controlFields2 = new byte[] { 0x84, 0x9C };
    var packageData2 = new byte[] { };

    zvtClient.CustomCommandAsync(controlFields2, packageData2);
}
```
this somewhat works, but when it get's out of timing the library acknowledges as success.

I'm up for ideas! Thanks in advance!

EDIT: I did some digging, there is the option to implement an own ReceiveHandler but this doesn't resolve the problem I think. This library seems to automatically acknowledge the request while in reality it should wait for dispense of product. So instead of answering the authorization request with 0x80 0x00 0x00, it should send 0x84 0x00 0x00 until the product is dispensed, then answer with the correct control field as seen in screenshots above.

EDIT2:

in ZvtCommunication.cs I changed this:

```C#
if (data[0] == 0x04 && data[1] == 0x0F)
{
    this._deviceCommunication.SendAsync(new byte[] { 0x84, 0x9C, 0x00});
}
else
{
    this._deviceCommunication.SendAsync(this._acknowledge);
}
```

this works, however to support this functionality I think the library has to be reworked at many places, am I right?

**Comment by tinohager** [comment]
Hi, i have not yet dealt with the subject of vending terminals enough. But I think the changes are manageable. Have they already tested their code whether they can subsequently change the amount?

**Comment by MLDMoritz** [comment]
Charging less than initially authorized is no problem. I do something like this:

In `ZvtCommunications.cs`
```C#
if (data[0] == 0x04 && data[1] == 0x0F)
{
    this._deviceCommunication.SendAsync(new byte[] { 0x84, 0x9C, 0x00});
}
else
{
    this._deviceCommunication.SendAsync(this._acknowledge);
}
```

In `Program.cs`
```C#

Task.Delay(15000).ContinueWith(t =>
{
    var controlFields2 = new byte[] { 0x84, 0x9D }; // 
    var package2 = new List<byte>();
    package2.Add(0x04); //Amount prefix
    package2.AddRange(NumberHelper.DecimalToBcd(5.5M));

    zvtClient.CustomCommandAsync(controlFields2, package2.ToArray());
});

var response = await zvtClient.PaymentAsync(10.5M);
```

![image](https://user-images.githubusercontent.com/46711821/160296597-3a928714-1765-4c60-a3bc-0b12bdee0009.png)

I am not really familiar with C# but I would love to help!

**Comment by tinohager** [comment]
How soon would they need the change? Your terminal is connected via Tcp right? Can you provide any information about which manufacturer/model you are testing with?

**Comment by MLDMoritz** [comment]
As always I would love to start immediately, but I think a month a so is fine. Connection is done via TCP. Regular paymentflow works just fine. Terminal is a PAX IM30, so relatively new and unknown. But feature seems to work with my hacky implementation tests.

I really don't want to just request this feature, if theres anything I can do I would really love to help!

**Comment by tinohager** [comment]
We also wanted to order the terminal, but they seem to have a shortage of equipment. :)

**Comment by MLDMoritz** [comment]
Ohh yes, they do have supply issues... I think this feature is not specific to the terminal however, should work on ther terminals too I think?

**Comment by tinohager** [comment]
I have now tried to reproduce the example on my vending terminal (worldline VALINA) but with me it aborts the process.

<HTML>
<BODY>
<TABLE><TR><TD>16.04.2022 22:52:08</TD><TD>ECR-&gt;PT</TD><TD>06-01-07-04-00-00-00-00-01-54</TD></TR><TR><TD>16.04.2022 22:52:08</TD><TD>PT-&gt;ECR</TD><TD>80-00-00</TD></TR><TR><TD>16.04.2022 22:52:09</TD><TD>PT-&gt;ECR</TD><TD>04-FF-2E-0A-01-06-2A-24-28-07-26-4B-61-72-74-65-20-76-6F-72-68-61-6C-74-65-6E-0A-65-69-6E-73-74-65-63-6B-65-6E-2F-64-75-72-63-68-7A-69-65-68-65-6E</TD></TR><TR><TD>16.04.2022 22:52:09</TD><TD>ECR-&gt;PT</TD><TD>80-00-00</TD></TR><TR><TD>16.04.2022 22:52:10</TD><TD>PT-&gt;ECR</TD><TD>04-FF-01-0E</TD></TR><TR><TD>16.04.2022 22:52:10</TD><TD>ECR-&gt;PT</TD><TD>80-00-00</TD></TR><TR><TD>16.04.2022 22:52:15</TD><TD>PT-&gt;ECR</TD><TD>04-0F-DB-27-00-04-00-00-00-00-01-54-0B-00-00-87-0C-22-51-47-0D-04-16-17-00-01-19-70-22-F0-F8-EE-EE-EE-EE-EE-EE-47-71-29-29-00-16-12-2A-31-30-30-36-38-36-30-32-31-20-20-20-20-20-20-3B-34-38-32-39-34-38-00-00-3C-F0-F1-F4-47-45-4E-2E-4E-52-2E-3A-34-38-32-39-34-38-49-09-78-87-00-87-88-00-00-87-8A-2E-8B-F1-F7-44-65-62-69-74-20-4D-61-73-74-65-72-63-61-72-64-00-06-65-24-10-07-0E-47-45-4E-2E-4E-52-2E-3A-34-38-32-39-34-38-43-07-A0-00-00-00-04-10-10-46-1F-41-30-30-30-30-30-30-30-30-34-31-30-31-30-20-42-46-33-46-45-43-36-45-39-33-39-32-30-43-30-34-47-1F-41-30-30-30-30-30-30-30-30-34-31-30-31-30-20-42-46-33-46-45-43-36-45-39-33-39-32-30-43-30-34-1F-10-01-00-1F-12-01-02</TD></TR><TR><TD>16.04.2022 22:52:15</TD><TD>ECR-&gt;PT</TD><TD>84-9C-00</TD></TR><TR><TD>16.04.2022 22:52:20</TD><TD>PT-&gt;ECR</TD><TD>04-0F-DB-27-00-04-00-00-00-00-01-54-0B-00-00-87-0C-22-51-47-0D-04-16-17-00-01-19-70-22-F0-F8-EE-EE-EE-EE-EE-EE-47-71-29-29-00-16-12-2A-31-30-30-36-38-36-30-32-31-20-20-20-20-20-20-3B-34-38-32-39-34-38-00-00-3C-F0-F1-F4-47-45-4E-2E-4E-52-2E-3A-34-38-32-39-34-38-49-09-78-87-00-87-88-00-00-87-8A-2E-8B-F1-F7-44-65-62-69-74-20-4D-61-73-74-65-72-63-61-72-64-00-06-65-24-10-07-0E-47-45-4E-2E-4E-52-2E-3A-34-38-32-39-34-38-43-07-A0-00-00-00-04-10-10-46-1F-41-30-30-30-30-30-30-30-30-34-31-30-31-30-20-42-46-33-46-45-43-36-45-39-33-39-32-30-43-30-34-47-1F-41-30-30-30-30-30-30-30-30-34-31-30-31-30-20-42-46-33-46-45-43-36-45-39-33-39-32-30-43-30-34-1F-10-01-00-1F-12-01-02</TD></TR><TR><TD>16.04.2022 22:52:20</TD><TD>ECR-&gt;PT</TD><TD>84-9D-07-04-00-00-00-00-00-99</TD></TR><TR><TD>16.04.2022 22:52:26</TD><TD>PT-&gt;ECR</TD><TD>06-1E-01-6C</TD></TR><TR><TD>16.04.2022 22:52:26</TD><TD>ECR-&gt;PT</TD><TD>80-00-00</TD></TR></TABLE>

</BODY>
</HTML>

**Comment by MLDMoritz** [comment]
Hey, thanks for looking into! I think `06 1E` is the error, `01` means it's an error sent by the network operator.

If you share your code I could run it on the PAX Device to see if it's a problem with the valina itself. The flow itself lgtm.

**Comment by tinohager** [comment]
we now also have a pax in the office i will try it there yet to test. My code is still in the early stages. Please still a little patience

**Comment by tinohager** [comment]
I have add a fork with the test code

**Comment by tinohager** [comment]
@MLDMoritz Can they provide feedback on that?

**Comment by MLDMoritz** [comment]
Sorry, I didn't see your comment! I will dig into now.

**Comment by MLDMoritz** [comment]
This is some wonky test code I used. At first sight, the implementation looks good and works as expected! Thanks for your help!
However, there might be some timing or timeout issue, I think; the below code works nearly all the time, but not every time and can produce an output as following:



```
dbug: Portalum.Zvt.ZvtClient[0]
      ProcessTlvInfoAction - No action defined for Tag:2F
info: Portalum.Zvt.ZvtClient[0]
      ParseInternal - Cannot found a process action for tag:1F11 Primitive
dbug: Portalum.Zvt.TcpNetworkDeviceCommunication[0]
      SendAsync - 84-9C-00
dbug: Portalum.Zvt.TcpNetworkDeviceCommunication[0]
      Receive - 84-83-00
fail: Portalum.Zvt.ZvtClient[0]
      DataReceived - Unprocessable data received 84-83-00
```



```C#
using Microsoft.Extensions.Logging;
using Portalum.Zvt;
using Portalum.Zvt.Models;
using Portalum.Zvt.Repositories;

using var loggerFactory = LoggerFactory.Create(builder => { builder.AddConsole().SetMinimumLevel(LogLevel.Debug); });

var deviceCommunicationLogger = loggerFactory.CreateLogger<TcpNetworkDeviceCommunication>();
var zvtClientLogger = loggerFactory.CreateLogger<ZvtClient>();

var deviceCommunication = new TcpNetworkDeviceCommunication("10.0.1.25", 20007, logger: deviceCommunicationLogger);
if (!await deviceCommunication.ConnectAsync()) return;

IErrorMessageRepository errorMessageRepository = new EnglishErrorMessageRepository();
IIntermediateStatusRepository intermediateStatusRepository = new EnglishIntermediateStatusRepository();

var zvtClientConfig = new ZvtClientConfig
{
    Password = 000000
};

var zvtClient = new ZvtClient(deviceCommunication, clientConfig: zvtClientConfig, logger: zvtClientLogger);

zvtClient.ReceiptReceived += (receipt) =>
{
    Console.Write(receipt.Content);
};


CompletionInfo HandleWait()
{
    return new CompletionInfo
    {
        Status = CompletionInfoStatus.Wait
    };
}

CompletionInfo HandleCompletion()
{
    return new CompletionInfo
    {
        Status = CompletionInfoStatus.Successful
    };
}


CompletionInfo HandleFailure()
{
    return new CompletionInfo
    {
        Status = CompletionInfoStatus.Failure
    };
}

CompletionInfo HandleChangeAmount()
{
    return new CompletionInfo
    {
        Status = CompletionInfoStatus.ChangeAmount,
        Amount = 5.5M
    };
}


zvtClient.AskForCompletionInfo += HandleWait;

Task.Delay(30000).ContinueWith(t =>
{
  //  zvtClient.AskForCompletionInfo -= HandleWait;
    zvtClient.AskForCompletionInfo += HandleChangeAmount;

});


var response = await zvtClient.PaymentAsync(10.5M);


switch (response.State)
{
    case CommandResponseState.Successful:
        Console.WriteLine("SUCCESS");
        break;
    case CommandResponseState.Abort:
        Console.WriteLine("USER ABORTED");
        break;
    case CommandResponseState.Error:
        Console.WriteLine("ERROR");
        break;
    case CommandResponseState.Timeout:
        Console.WriteLine("TIMEOUT");
        break;
    case CommandResponseState.Unknown:
        break;
    case CommandResponseState.NotSupported:
        break;
    default:
        throw new ArgumentOutOfRangeException();
}
```

**Comment by tinohager** [comment]
84-83-00 is "Other Commands" -> In response to other commands not described in this specification, or not supported by the PT

**Comment by MLDMoritz** [comment]
This happened two or three times but I cannot really reproduce it right now :-(. Instead of the partial charge, it should've done, it showed an error of product dispensal.

**Comment by tinohager** [comment]
As far as I know the CCV protocol is still under development according to our conversation with CCV we currently have a prerelease version that should work better but is not released yet.

**Comment by MLDMoritz** [comment]
My terminal is on version 24 with enhanced ZVT Support, it should be the latest one. I will observe if it happens again.

**Comment by tinohager** [comment]
Is there an update on this issue?

**Comment by MLDMoritz** [comment]
Hi Tino,

sorry for the late response. I think we need another State to represent a successfull authorization, so we know when to start dispense the product.
