### ISSUE TITLE
Can't connect to terminal

### ISSUE THREAD

**Issue by truejp** [Portalum/Portalum.Zvt#16]
### NuGet Package Version

2.15.0

### Payment service provider

TeleCash

### Payment terminal

cVEND box+ topp

### Communication Logs

[connection_log.pdf](https://github.com/Portalum/Portalum.Zvt/files/8750445/connection_log.pdf)

This is an export of Wireshark Logging from all communication with the terminal. The first entries until including time 5.111288 are made using the ZVT Library, the ones afterwards are from a successful connection using the official management tool CRS. Default Port for unencrypted communication is 22000, with SSL its 22001. I've used 22000.

### More information

I cannot get a successful connection to my cash terminal, but I've tested it successfully with other tools like EasyZVT. I'd like to start my own implementation into my application, so this library seems like a very good fit. I'm not quite sure why the connection won't work. Default character set of this terminal is ISO-8859-1. Please let me know if you need any more information to help fix this issue.

**Comment by tinohager** [comment]
Have they tested it with our ControlPanel?

**Comment by truejp** [comment]
It was tested with both the ControlPanel and the smaller version (just for amount) as well as the library itself.
Thanks
Philipp

**Comment by truejp** [comment]
I can't even connect to the device, the logs from my previous post were the unsuccessful attempt of connecting. The interface states "try connect [terminal ip adress]", then it states "cannot  connect". All other buttons of course give back error "ZVT Client not ready" on the right hand side. Communication Tab has no contents. The logfile of the ControlPanel states "12:30:12.509 INF Portalum.Zvt.TcpNetworkDeviceCommunication ConnectAsync" all over again, just the time is adjusted. 

![image](https://user-images.githubusercontent.com/80537345/169800565-bc5084b4-674f-49b9-a369-9d6418d7ebee.png)

The Log of easyPay gives more details:

`00:37:43.788 INF Portalum.Zvt.EasyPay.App App - Start
00:37:43.893 INF Portalum.Zvt.EasyPay.App RunOptions - Startup successful, start payment process wiht an amount of 0,01
00:37:44.053 INF Portalum.Zvt.EasyPay.MainWindow StartPaymentAsync - Start
00:37:44.342 INF Portalum.Zvt.TcpNetworkDeviceCommunication ConnectAsync
00:37:49.419 ERR Portalum.Zvt.EasyPay.MainWindow StartPaymentAsync - Cannot connect to 192.168.0.142:20001
00:37:49.429 INF Portalum.Zvt.EasyPay.App Application_Exit - Exit`

**Comment by tinohager** [comment]
same with port 22000?

**Comment by truejp** [comment]
Yes, I've tried them both.
`00:36:54.145 INF Portalum.Zvt.EasyPay.App App - Start
00:36:54.274 INF Portalum.Zvt.EasyPay.App RunOptions - Startup successful, start payment process wiht an amount of 0,01
00:36:54.440 INF Portalum.Zvt.EasyPay.MainWindow StartPaymentAsync - Start
00:36:54.715 INF Portalum.Zvt.TcpNetworkDeviceCommunication ConnectAsync
00:36:59.786 ERR Portalum.Zvt.EasyPay.MainWindow StartPaymentAsync - Cannot connect to 192.168.0.142:20000
00:36:59.798 INF Portalum.Zvt.EasyPay.App Application_Exit - Exit`

This issue looks pretty odd to me since the initial communication logs look pretty similar. I thought about it maybe being an issue related to the "listening" Port on the PC running the Software, since this differs. I've not hat the time rerouting the ports yet, I'll maybe try this later too.

**Comment by tinohager** [comment]
> Default Port for unencrypted communication is 22000, with SSL its 22001. I've used 22000.

you have write `22000` is the default and not `20000`

**Comment by truejp** [comment]
Oh boi, this is embarrassing... You have a donation link for a cup of coffee by any chance?

**Comment by tinohager** [comment]
https://www.paypal.com/paypalme/nagerat ☕ 😄
