### ISSUE TITLE
Net Framework 4.6 support available?

### ISSUE THREAD

**Issue by Proggopogo** [Portalum/Portalum.Zvt#2]
Hello, I have a question to the library as a whole:

When using a standard console Application, the library works just fine! However, I am unable to install it on a winforms application using the .NET Framework 4.6.2 and upwards. The console is throwing an error, stating that there are no assembly informations for the project. Am I doing something wrong or is there a simple way to fix that?

**Comment by tinohager** [comment]
Is there a reason why they can't use .NET 5/6?

**Comment by tinohager** [comment]
I have push a new package with .netstandard 2.0 support with this package you have support for net 4.6.1
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by tinohager** [comment]
The new package is available can you test with it again?

**Comment by Proggopogo** [comment]
I will do that right away

**Comment by Proggopogo** [comment]
Works! Thanks!

**Comment by tinohager** [comment]
We would love a star for our project ⭐
