### ISSUE TITLE
Repeat Receipt not printing previous transaction

### ISSUE THREAD

**Issue by mBednarz92** [Portalum/Portalum.Zvt#26]
### Payment service provider

Global Payments

### Payment terminal

PAX A80

### Communication Logs

06-20-03-00-00-00
80-00-00
06-0F-00
80-00-00

### More information

I am facing this issue only when set to 'true' the following values:

`AllowAdministrationViaPaymentTerminal = true,
 AllowStartPaymentViaPaymentTerminal = true,`

With that, all payments, refunds, etc. are printed receipts very well, but I am not able to 'RepeatReceipt (06 20). I tried it with my implementation and also with Portalum ControlPanel. Same issue. 

It is funny cause when I set this value like this:

`AllowAdministrationViaPaymentTerminal = false,
 AllowStartPaymentViaPaymentTerminal = false,`

then, I am able to grab the last receipt as a String from StatusInformation, or same it is printed on screen with Portalum ControlPanel.

When I am using 'Belegskopie' directly from the terminal device It is printing the receipt normally.

Unfortunately, I am not able to check it with other ZVT-based devices so I am wondering if it is just a bug or if only my GP PAX80 device is behaving like that.

**Comment by tinohager** [comment]
We have not had a good experience with Global Payments terminals, the ZVT standard does not seem to be 100% implemented yet.

**Comment by tinohager** [comment]
Is there anything else or can we close the issue?

**Comment by mBednarz92** [comment]
Feel free to close it, I will check that behavior with a device from another provider. If it will happen again, I will take a look and maybe solve it. I let you know. Thanks!!!
