### ISSUE TITLE
Is Using the program as an Emulator with a different langage program

### ISSUE THREAD

**Issue by dasilvasuzy** [Portalum/Portalum.Zvt#27]
### Payment service provider

Visa

### Payment terminal

ingenico

### More information

Hello, i'd like to know if it's possible to use the program as an emulator? I do not use c# but i can add .dll libraries to my project. The more i read the code and the information i try to wonder if it's possible to use it as an emulator or you need a real EPT ? 

Thank you, sorry for the bother I'm a begginer and I have a task to code a EPT communication but I cannot test it :/

**Comment by tinohager** [comment]
Hi, sorry this project is not a simulator, it need a real hardware.

**Comment by dasilvasuzy** [comment]
thank you very much for your fast anwser, the project is very cool maybe i'd get to use it if i get a real hardware.
best wishes
