### ISSUE TITLE
Terminal PAX A80

### ISSUE THREAD

**Issue by micblazek** [Portalum/Portalum.Zvt#28]
### Payment service provider

SaltPay

### Payment terminal

PAX A80

### Communication Logs

14:35:23.910 INF Portalum.Zvt.TcpNetworkDeviceCommunication ConnectAsync
14:46:30.399 INF Portalum.Zvt.TcpNetworkDeviceCommunication ConnectAsync
14:46:35.256 INF Portalum.Zvt.TcpNetworkDeviceCommunication ConnectAsync
14:46:53.963 INF Portalum.Zvt.TcpNetworkDeviceCommunication ConnectAsync
14:47:05.367 INF Portalum.Zvt.TcpNetworkDeviceCommunication ConnectAsync

### More information

Could someone advise me how to connect to the PAX A80 payment terminal.

I tried the recommended ports 20007 and 20008 and all encoding options but no luck. Is there an application that needs to be installed or run in the terminal?

How would I find out what port and encoding to use?

**Comment by tinohager** [comment]
Are you sure that SaltPay supports zvt? This is used in Germany and Austria.

**Comment by micblazek** [comment]
Thanks for the direction. I will try to find out, I didn't know that ZVT was something special.

**Comment by tinohager** [comment]
In every country there is a perceived standard of its own :)
