### ISSUE TITLE
Missing entries in IntermediateStatusRepository [Ingenico] 

### ISSUE THREAD

**Issue by SRouven** [Portalum/Portalum.Zvt#29]
### Payment service provider

Secupay

### Payment terminal

Ingenico Link 2500

### Communication Logs

[communication-export-2023-37-13-01-37-59.json.log](https://github.com/Portalum/Portalum.Zvt/files/10411586/communication-export-2023-37-13-01-37-59.json.log)

### More information

For Ingenico terminals the IntermediateStateRepository is missing the entries 0xA0 to 0xA5. 
(Line 155 in the logs and "Timestamp": "2023-01-13T13:14:20.9553244+01:00")

Looks like Ingenico expanded this on its own. 
Documented here (p.82f) : 
https://cdn.ingenico.com/binaries/content/assets/germany-smart-terminals/ersatz-und-zuberhorteile/--3.x--schnittstellendoc/a32.de_zvt_ecr_interface_en_v1.3.41-customer.pdf

I'm not sure if you want to take that into account, but i´ll have to add this and wanted to let you know.

Best regards

**Comment by tinohager** [comment]
I think we only need a own IIntermediateStatusRepository for Ingenico with the additional codes.
Or have I missed a case?

**Comment by SRouven** [comment]
Those codes (A0-A5) are not in use, officially. So, for now, i wouldn´t mind, if they are simply added, to the existing repositories.
This would avoid having to worry about additional configuration.

**Comment by SRouven** [comment]
That's legit.

**Comment by SRouven** [comment]
Problem solved, thank you.
