### ISSUE TITLE
How to create a functional payment process?

### ISSUE THREAD

**Issue by Proggopogo** [Portalum/Portalum.Zvt#3]
Hello again! I'm still working on my little terminal application, and I ran into some issues. With your changes, starting a payment is a breeze, but finishin it just doesn't work. After starting a payment, I insert the card into the machine, enter the pincode, and promptly receive the message "Payment aborted". I really would like to push a payment through, but I don't have the knowledge of the library to create the neccessary steps. @tinohager, can you help me out again? Also, the machine is able to create a receipt on its own. How do I fetch that receipt? 

Edit: It worked once per NFC reader, but not through the regular card reader.

**Comment by tinohager** [comment]
have you receive my email?

**Comment by Proggopogo** [comment]
An email? I don't know what you mean...

**Comment by tinohager** [comment]
Can I reach you at info@trefon.de?

**Comment by Proggopogo** [comment]
No, that's the company email. You can reach me at mm@trefon.de

**Comment by Proggopogo** [comment]
I received your email.
