### ISSUE TITLE
Resolving the "Card unnkown" error

### ISSUE THREAD

**Issue by Proggopogo** [Portalum/Portalum.Zvt#4]
Hello again, I had some time left today and tried to catch some error messages with the terminal. I tried a payment again and started catching error messages. One of them was the "card unknown" error, which I don't know how to fix. It's a simple Maestro Card with girocard on it. Using it via the NFC card reader works, but it using the card reader doesn't. Any ideas how to fix that? Do i need to add this card type before I try to pay with it?

**Comment by tinohager** [comment]
Which payment service provider do they use in the background? Have you already contacted them?

**Comment by Proggopogo** [comment]
It's a payment simulation the terminal, issued by the company building it, verifone.

**Comment by Proggopogo** [comment]
It was a card specific error. A Mastercard worked just fine.
