### ISSUE TITLE
Suppressing the receipt printout

### ISSUE THREAD

**Issue by mauveSchlueter** [Portalum/Portalum.Zvt#45]
### Payment service provider

PAYONE

### Payment terminal

ingenico Move/3500

### More information

Is there any possibility to suppress the printout of the merchant receipt? We want to print the merchant receipt on a dedicated receipt printer and therefore have no need for the receipt printed by the terminal.

**Comment by tinohager** [comment]
https://github.com/Portalum/Portalum.Zvt/blob/f7e5607836f0018c473558794e2b46eecb5a78c9/src/Portalum.Zvt/RegistrationConfig.cs#L15

**Comment by mauveSchlueter** [comment]
Thanks a lot for the quick reply, this is exactly what I was looking for!
