### ISSUE TITLE
How do I allow and deny certain cards?

### ISSUE THREAD

**Issue by Proggopogo** [Portalum/Portalum.Zvt#5]
Hello once more! I was wondering if there was a way to deny certain cards on the terminal or allow them, e.g. don't allow the usage of American Express, Discovercards, Alipay, etc. or only allow Girocards, Visa and Mastercard, etc.?

**Comment by tinohager** [comment]
Here is the documentation https://www.terminalhersteller.de/downloads/PA00P015_13.09_final_en.pdf

**Comment by Proggopogo** [comment]
I took a look through that and saw the card ID's. In your library, you defined a bunch of card informations. If I remove the ones I don't want to be supported, will it abort the payment right away?

**Comment by tinohager** [comment]
I rather think that you would have to define special cards via a TLV command here

**Comment by Proggopogo** [comment]
I figured that. This was more of a regular question. Turns out that the provider for the terminal decides which cards are allowed and which are denied.
