### ISSUE TITLE
girocard issues

### ISSUE THREAD

**Issue by Proggopogo** [Portalum/Portalum.Zvt#6]
Hello, I am running into issues with girocards. They work via NFC, but never via the terminal. I tested a bunch of cards, and every payment method works, only girocard via pinpad doesn't. Any ideas why?

**Comment by tinohager** [comment]
what does the log file say?

**Comment by Proggopogo** [comment]
The TestUi doesn't work for me, even after I modified the code with the port and password, so I used my own application. I request Cardtype and error messages. The issue doesn't seem to be girocard on it's own, but rather cards that have multiple payment options. I have a Mastercard here with both Giropay and Mastercard on it. When I insert it into the terminal, it asks me which payment option I want to use. If I select Mastercard and enter the pin, it works fine. If I select girocard and do the same, it aborts the payment. I receive the card type "girocard", followed by the error message "card unknown", and an abort. Similar issues occur with a Maestrocard and one that inlcudes Vpay alongside girocard. Using them via NFC works tho.

**Comment by tinohager** [comment]
And what is in the log file of the TestUi can you show the communication history?

**Comment by Proggopogo** [comment]
This is the log entry:

11:08:51.617 INF Portalum.Zvt.TcpNetworkDeviceCommunication Connected 192.168.0.77:22000
11:08:56.655 INF Portalum.Zvt.ZvtClient PaymentAsync - Execute with amount of:0,01
11:08:56.658 DBG Portalum.Zvt.ZvtClient SendCommandAsync - Send command to PT
11:08:56.660 DBG Portalum.Zvt.TcpNetworkDeviceCommunication SendAsync - 06-01-07-04-00-00-00-00-00-01
11:08:56.692 DBG Portalum.Zvt.TcpNetworkDeviceCommunication Receive - 80-00-00
11:09:07.713 DBG Portalum.Zvt.TcpNetworkDeviceCommunication Receive - 04-0F-6B-27-7A-04-00-00-00-00-00-01-0B-00-00-79-0C-11-07-35-0D-11-29-0E-25-12-17-00-01-19-70-22-F1-F0-68-05-90-44-11-00-10-05-41-4F-29-75-01-13-41-87-00-17-8A-05-8C-00-8B-F0-F9-67-69-72-6F-63-61-72-64-00-06-28-2F-0C-1F-10-01-00-1F-11-01-01-1F-12-01-01-60-0C-43-0A-A0-00-00-03-59-10-10-02-80-01-45-04-21-00-00-00-1F-16-03-01-FC-3B
11:09:07.714 DBG Portalum.Zvt.TcpNetworkDeviceCommunication SendAsync - 80-00-00
11:09:07.720 INF Portalum.Zvt.ZvtClient Parse - No parser available for 0D Date, format MMDD (see also AA)
11:09:07.720 INF Portalum.Zvt.ZvtClient Parse - No parser available for 19 Status-byte as defined in Registration (06 00) / Payment-type as defined in Authorization (06 01) / Card-type as defined in Read Card (06 C0)
11:09:07.720 INF Portalum.Zvt.ZvtClient Parse - No parser available for 22 PAN / EF_ID, 'E' used to indicate a masked numeric digit1. If the card-number contains an odd number of digits, it is padded with an ‘F’.
11:09:07.721 INF Portalum.Zvt.ZvtClient Parse - No parser available for 8C Card-type-ID of the network operator (see also 8A)
11:09:07.725 DBG Portalum.Zvt.ZvtClient ProcessTlvInfoAction - No action defined for Tag:2F
11:09:07.725 INF Portalum.Zvt.ZvtClient ParseInternal - Cannot found a process action for tag:1F11 Primitive
11:09:07.726 INF Portalum.Zvt.ZvtClient ParseInternal - Cannot found a process action for tag:60 Constructed
11:09:07.726 INF Portalum.Zvt.ZvtClient ParseInternal - Cannot found a process action for tag:43 Primitive
11:09:07.726 INF Portalum.Zvt.ZvtClient ParseInternal - Cannot found a process action for tag:45 Primitive
11:09:07.726 INF Portalum.Zvt.ZvtClient ParseInternal - Cannot found a process action for tag:1F16 Primitive
11:09:07.766 DBG Portalum.Zvt.TcpNetworkDeviceCommunication Receive - 06-1E-3C-7A-06-39-49-01-00-2F-0C-1F-10-01-00-1F-11-01-01-1F-12-01-01-60-10-41-02-00-05-43-0A-A0-00-00-03-59-10-10-02-80-01-08-02-00-17-1F-2B-03-00-00-79-45-04-21-00-00-00-1F-16-03-01-FC-3B
11:09:07.766 DBG Portalum.Zvt.TcpNetworkDeviceCommunication SendAsync - 80-00-00
11:09:07.766 DBG Portalum.Zvt.ZvtClient ProcessData - 'Abort' received card unknown

**Comment by tinohager** [comment]
The Payment Terminal send direct after Authorization (06 01), this feedback

![image](https://user-images.githubusercontent.com/8215186/143853652-234ce8b1-1403-4420-8410-889e122c51a5.png)

I have never received this command on my terminals - it has yet to be implemented, Abort (06 1E)
`06-1E-3C-7A-06-39-49-01-00-2F-0C-1F-10-01-00-1F-11-01-01-1F-12-01-01-60-10-41-02-00-05-43-0A-A0-00-00-03-59-10-10-02-80-01-08-02-00-17-1F-2B-03-00-00-79-45-04-21-00-00-00-1F-16-03-01-FC-3B`

**Comment by Proggopogo** [comment]
I don't really know what to do with this error. especially since NFC works just fine, even via girocard. Do you have any idea how to resolve this issue? Any help would be appreciated.

**Comment by tinohager** [comment]
Have they contacted their payment provider with this error yet?

**Comment by Proggopogo** [comment]
I'll give that a shot. I couldn't find anything regarding that issue online. Maybe it has to do with the cards being prepaid ones, fleet cards basically. But that still doesn't explain why the raw girocard works.

**Comment by Proggopogo** [comment]
I contacted the terminal company and found out that Debit cards aren't allowed. The two testing cards causing me trouble are probably getting treated as such, and thus are being denied. That explains it.
