### ISSUE TITLE
How do I receive all status informations?

### ISSUE THREAD

**Issue by Proggopogo** [Portalum/Portalum.Zvt#7]
I want to receive all informations from a payment when it's being taken. The StatusInformationReceived Event handler contains these informations, like receipt number, Amount, Expirydate, Tracenumber, etc. If I write a simple event like: 

`            Payment.Terminal.StatusInformationReceived += (Infos) => UpdateTextbox(Infos.ExpiryDateMonth.ToString());`
(UpdateTextbox just sends the text to a function that looks whether a delegate is neccessary or not, and then appends the text onto the texbox), nothing comes over when a payment is taken. Do I need to specify that somewhere?

**Comment by tinohager** [comment]
Sorry the project is open source but there is not a free support for the implementation here.

**Comment by Proggopogo** [comment]
Alright then.
